name: RSP
main: me.asofold.bpl.rsp.RSP
version: 1.3.4
softdepend:
- WorldGuard
- PermissionsEx
- bPermissions
- Vault

commands:
  rsp: 
     description: 'For managing RSP: /rsp <cmd>... for: | reload | info | stats | stats reset | stats off | stats on | ping ... (permissions)'
     usage: 'For managing RSP: /rsp <cmd>... for: | reload | info | stats | stats reset | stats off | stats on | ping ... (permissions)'

